model_args:
  model_name_or_path: ModernVBERT/modernvbert
  model_type: ModernVBertSparse
  sparse_dim: 128
  loading_kwargs:
    torch_dtype: bfloat16
    trust_remote_code: true

train_dataset_args:
- dataset_name_or_path: manu/colpali-queries
  loading_kwargs:
    num_negs: 1

tr_args:
  output_dir: models/modernvbert_sparse
  num_train_epochs: 3
  per_device_train_batch_size: 4
  learning_rate: 2e-4
  warmup_ratio: 0.1
  bf16: true
  report_to: wandb
