model_args:
  model_name_or_path: SmolVEncoder/vllama_anneal30_mlm
  model_type: BiEuroVBert
  loss_type: BiEncoderLoss
  loading_kwargs:
    attn_implementation: flash_attention_2
    torch_dtype: bfloat16
    trust_remote_code: true
train_dataset_args:
- dataset_name_or_path: vidore/colpali_train_set
  loading_kwargs:
    split: train
eval_dataset_args:
- dataset_name_or_path: vidore/colpali_train_set
  loading_kwargs:
    split: test
tr_args:
  output_dir: /lustre/fsn1/projects/rech/nwd/uyn61im/checkpoints/experiments/vbert/ablations/alignment_objective/bivllama_anneal30_mlm
  num_train_epochs: 1
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  eval_strategy: 'no'
  save_strategy: epoch
  logging_steps: 1
  warmup_ratio: 0.1
  learning_rate: 0.0002
  run_name: alignment_objective__bivllama_anneal30_mlm
  report_to: wandb
lora_config:
  r: 32
  lora_alpha: 32
  lora_dropout: 0.1
  init_lora_weights: gaussian
  bias: none
  task_type: FEATURE_EXTRACTION
  target_modules: (.*(model.text_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$)
eval_config:
  wrapper_cls: BiEuroVBertWrapper
  tasks:
  # Document retrieval.
  - VidoreArxivQARetrieval
  - VidoreDocVQARetrieval
  - VidoreInfoVQARetrieval
  - VidoreTabfquadRetrieval
  - VidoreTatdqaRetrieval
  - VidoreShiftProjectRetrieval
  - VidoreSyntheticDocQAAIRetrieval
  - VidoreSyntheticDocQAEnergyRetrieval
  - VidoreSyntheticDocQAGovernmentReportsRetrieval
  - VidoreSyntheticDocQAHealthcareIndustryRetrieval
  - Vidore2ESGReportsRetrieval
  - Vidore2EconomicsReportsRetrieval
  - Vidore2BioMedicalLecturesRetrieval
  - Vidore2ESGReportsHLRetrieval
  batch_size: 32
  output_folder: /lustre/fswork/projects/rech/nwd/uyn61im/visual_encoder/posttraining/ablations/alignment_objective/results
  encode_kwargs: {}
