#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=Contrastive
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --time=00:02:00
#SBATCH --output=output/make_cpt_%A.out


module purge
module load 2025
module load Anaconda3/2025.06-1
module load CUDA/12.8.0


# Your job starts in the directory where you call sbatch
cd $HOME/modernvbert
# Activate your environment
source activate modernvbert
# Run your code
srun python make_cpt_new.py
